### ISSUE TITLE
Error checking

### ISSUE THREAD

**Issue by yeungs** [daptiv/visualstudio#16]
I execute the recipe on a few machines with no problems. Then on one machine the recipe executed without but the Visual Studio 2012 didn't get installed (nothing but the uninstall.log in the installation folder). 

So I dig deeper and try to see what files were extracted from the ISO. Look at the AdminDeployment.xml file to compare what I did. Then I finally read the vsinstall.log. I found out my system didn't have enough disk space to begin the install. ;)

Can I update the install.rb to do "is_vs_installed?()" again after the install and before the extracted folder is deleted to determine if the installation succeeded? We can then add  code to grep out the exit code in the vsinstall.log and display it if before exiting as error. 

It is not perfect but can catch a few use cases.

**Comment by sneal** [comment]
The best solution is to run the minitests which will validate the VS was properly installed. Just add the `minitest-handler` to your Chef run_list.
