### ISSUE TITLE
Push version tags to GitHub repo

### ISSUE THREAD

**Issue by legal90** [daptiv/visualstudio#29]
Hi! Thank you for this useful cookbook!

I noticed that some versions have been released on the supermarket: https://supermarket.chef.io/cookbooks/visualstudio
Could you please push the appropriate version tags (`v0.1.0`, `v1.0.0`, etc.) to the GitHub repo? They help to find the revision where the concrete version has been released. Thanks!

cc: @sneal

**Comment by sneal** [comment]
Done. Retroactively added the v1.0.0 tag and also released a new version 1.0.1 with several bug fixes for VS 2015. The 0.1.0 version on Chef SuperMarket is from the old cookbook which came from a different repository, so I have no way to tag that here. Fortunately the SuperMarket cookbook owner transferred the ownership to me so I could update it.
