### ISSUE TITLE
Box not found

### ISSUE THREAD

**Issue by smallen3** [daptiv/visualstudio#31]
Vagrant up returns
The box 'daptiv/windows2012r2_chef11' could not be found or
could not be accessed in the remote catalog. If this is a private
box on HashiCorp's Atlas, please verify you're logged in via
`vagrant login`. Also, please double-check the name. The expanded
URL and error message are shown below:

URL: ["https://atlas.hashicorp.com/daptiv/windows2012r2_chef11"]
Error: The requested URL returned error: 404 Not Found

**Comment by sneal** [comment]
The referenced box lives our private server because of Windows licensing restrictions. You can update the box and box_url to your own Windows Vagrant base box.
