### ISSUE TITLE
VS2010 Pro install fails with exit code 1603

### ISSUE THREAD

**Issue by rkersh** [daptiv/visualstudio#36]
I should preface this by saying that I'm very new to Chef.  If there's a log file or something like this that would be useful let me know.

This error occurred on Windows 8.1 VL x64.
The first time I ran the install recipe the system rebooted (not sure why, AFAIK the .NET framework v4.5 is already installed).
I ran the recipe a second time and it failed with an exit code of 1603 (I've attached the console output).
[chef-visualstudio-install.txt](https://github.com/daptiv/visualstudio/files/31412/chef-visualstudio-install.txt)

In c:\Users\rkersh\AppData\Local\Temp\dd_install_vs_procore_100.txt, I see the following:
[11/10/15,15:50:07] Setup.exe: GetGlobalCustomProperty - Property: {383F0141-C682-4665-A69B-756E719C968D} - PropertyName: Process Return Code - Value: 1603
[11/10/15,15:50:07] Setup.exe: SETUP EXIT CODE - 1603
[11/10/15,15:50:07] End_Session: 

I have only tried this once.  I will try to reproduce this on a clean VM to see if the same thing happens.

**Comment by sneal** [comment]
I suspect this is a permissions issue with WinRM.

This needs to be added to the readme, but the cookbook will not work via test-kitchen or knife which use raw WinRM to invoke Chef. The cookbook will work when run locally or via Vagrant and Packer because they use a scheduled task under the cover to invoke Chef thus breaking out of the WinRM sandbox.

**Comment by rkersh** [comment]
I've been using local-mode from a "Run as Administrator" PowerShell, like so:
```
chef-client --local-mode --runlist 'recipe[visualstudio]'
```

**Comment by rkersh** [comment]
I reproduced the issue on a clean Windows Server 2012 R2 x64 VM.  @sneal, from your comment it sounds like this should work fine as I'm running in local-mode.

**Comment by sneal** [comment]
@rkersh VS 2015 requires .NET 4.6 to be installed, not 4.5.x. Also, take a look at the log from the VS installer. The install log is located at c:\program files (x86)\Micrsoft Visual Studio 14.0\vsinstall.log

**Comment by rkersh** [comment]
@sneal, the issue is with **VS 2010**, not VS 2015.  I mentioned .NET framework 4.5 above because the README says "This cookbook assumes .NET 4.5/4.6 has already been installed and rebooted the system before running the VisualStudio cookbook."  My VM did reboot when I tried installing with this cookbook the first time, but I'm not sure why (Windows 8.1 comes with .NET framework 4.5 by default, I believe).

For the record, with all other things being equal in my environment, the VS 2013 install works fine (I happened to have the ISO handy, that's why I tried it).

**Comment by sneal** [comment]
@rkersh I only tried installed VS 2010 on an older OS, Windows 2008R2. Have you tried to manually install VS 2010 via the GUI? Its possible it'll refuse installation on newer OSs.

**Comment by rkersh** [comment]
@sneal, I haven't tried that.  I'll give it a go and let you know how it goes.

**Comment by rkersh** [comment]
@sneal, I was able to install VS 2010 manually (and SP1) on Windows 8.1 x64 without any issues.  I used all default options.  This was not on a pristine VM, but it was fairly clean.

**Comment by aogail** [comment]
I also ran into this 1603 exit code. In my case I was installing VS 2010 on Windows 2012 R2. I worked around it by creating and using a new unattend.ini file. Just a guess: Perhaps the unattend.ini file created by VS 2010 on an older version of Windows is unusable for installing on newer versions.

**Comment by sneal** [comment]
Should be fixed by #46
