### ISSUE TITLE
No Start Menu Shortcuts

### ISSUE THREAD

**Issue by JakeStevenson** [daptiv/visualstudio#51]
When using this cookbook it appears to have installed the product, but no shortcuts are made to the start menu for visual studio or other tools.

My config:

    config.vm.provision :chef_solo do |chef|
    chef.add_recipe 'visualstudio::default'
    chef.add_recipe 'visualstudio::install_update'
    chef.add_recipe 'minitest-handler'
    chef.file_cache_path = 'c:/var/chef/cache' # Need leading drive letter
    chef.json = {
      'visualstudio' => {
        'version' => '2015',
        'edition' => 'enterprise',
        'source' => ENV['VS_SOURCE_URL'],
        'preserve_extracted_files' => false
      }
    }
  end

Run against a windows 10 box with the latest updates.  I am able to launch vs.net 2015 by navigating to the devenv.exe file.

**Comment by sneal** [comment]
How are you running the cookbook? Are you executing Chef under the same user as you're starting VS as?

**Comment by JakeStevenson** [comment]
Sorry, I forgot to mention I'm using Vagrant to do this.  I took this code almost directly from the Vagrantfile included in the cookbook.

I'm unsure what user it is attempting to run as, I haven't specified anything.  I'll have to dig deeper to see if I can find any information about that.

**Comment by JakeStevenson** [comment]
Seems I was mistaken, or maybe it needed a reboot.  The shortcuts appear as expected now.
