### ISSUE TITLE
Not able to install visual studio 2015 on Windows 2012R2

### ISSUE THREAD

**Issue by rajeshapt** [daptiv/visualstudio#52]
am getting some undefined method '[]' for nil:NilClass error. The output is below. Not sure if am doing something wrong. Please help
Cookbook Trace:
---------------
  c:/chef/cache/cookbooks/visualstudio/recipes/install.rb:32:in `block in from_file'
  c:/chef/cache/cookbooks/visualstudio/recipes/install.rb:27:in `each'
  c:/chef/cache/cookbooks/visualstudio/recipes/install.rb:27:in `from_file'
  c:/opscode/chef/embedded/apps/chef/lib/chef/mixin/from_file.rb:30:in `instance_eval'
  c:/opscode/chef/embedded/apps/chef/lib/chef/mixin/from_file.rb:30:in `from_file'
  c:/opscode/chef/embedded/apps/chef/lib/chef/cookbook_version.rb:228:in `load_recipe'
  c:/opscode/chef/embedded/apps/chef/lib/chef/run_context.rb:173:in `load_recipe'
  c:/opscode/chef/embedded/apps/chef/lib/chef/run_context/cookbook_compiler.rb:140:in `block in compile_recipes'
  c:/opscode/chef/embedded/apps/chef/lib/chef/run_context/cookbook_compiler.rb:138:in `each'
  c:/opscode/chef/embedded/apps/chef/lib/chef/run_context/cookbook_compiler.rb:138:in `compile_recipes'
  c:/opscode/chef/embedded/apps/chef/lib/chef/run_context/cookbook_compiler.rb:75:in `compile'
  c:/opscode/chef/embedded/apps/chef/lib/chef/run_context.rb:96:in `load'
  c:/opscode/chef/embedded/apps/chef/lib/chef/policy_builder/expand_node_object.rb:87:in `setup_run_context'
  c:/opscode/chef/embedded/apps/chef/lib/chef/client.rb:256:in `setup_run_context'
  c:/opscode/chef/embedded/apps/chef/lib/chef/client.rb:454:in `run'
  c:/opscode/chef/embedded/apps/chef/lib/chef/application.rb:253:in `run_with_graceful_exit_option'
  c:/opscode/chef/embedded/apps/chef/lib/chef/application.rb:230:in `block in run_chef_client'
  c:/opscode/chef/embedded/apps/chef/lib/chef/local_mode.rb:39:in `with_server_connectivity'
  c:/opscode/chef/embedded/apps/chef/lib/chef/application.rb:213:in `run_chef_client'
  c:/opscode/chef/embedded/apps/chef/lib/chef/application/client.rb:402:in `block in interval_run_chef_client'
  c:/opscode/chef/embedded/apps/chef/lib/chef/application/client.rb:392:in `loop'
  c:/opscode/chef/embedded/apps/chef/lib/chef/application/client.rb:392:in `interval_run_chef_client'
  c:/opscode/chef/embedded/apps/chef/lib/chef/application/client.rb:382:in `run_application'
  c:/opscode/chef/embedded/apps/chef/lib/chef/application.rb:60:in `run'
  c:/opscode/chef/embedded/apps/chef/bin/chef-client:26:in `<top (required)>'
  c:/opscode/chef/bin/chef-client:63:in `load'
  c:/opscode/chef/bin/chef-client:63:in `<main>'
 
Relevant File Content:
----------------------
c:/chef/cache/cookbooks/visualstudio/recipes/install.rb:
 
25:
26:  # Install each specified edition/version
27:  installs.each do |install|
28:    version = install['version']
29:    edition = install['edition']
30:
31:    install_url = File.join(node['visualstudio']['source'],
32>>                           node['visualstudio'][version][edition]['filename'])
33:
34:    visualstudio_edition "visualstudio_#{version}_#{edition}" do
35:      edition edition
36:      version version
37:      install_dir node['visualstudio'][version]['install_dir']
38:      source install_url
39:      product_key node['visualstudio'][version][edition]['product_key']
40:      package_name node['visualstudio'][version][edition]['package_name']
41:      checksum node['visualstudio'][version][edition]['checksum']
 
 
Running handlers:
Running handlers complete
Chef Client failed. 0 resources updated in 31.203136 seconds
PS C:\>

**Comment by sneal** [comment]
Which edition of VS 2015 are you attempting to install? This cookbook currently only supports: 'professional', 'community', 'enterprise'.

**Comment by rajeshapt** [comment]
community

**Comment by rajeshapt** [comment]
I tried to run the cookbook from my vagrant box(Win 2012R2) still am getting the error. I have copied below..It may help to identify the issue?
NoMethodError
-------------
undefined method `[]' for nil:NilClass
 
Cookbook Trace:
---------------
  C:\chef\cookbooks\visualstudio\recipes\install.rb:32:in `block in from_file'
  C:\chef\cookbooks\visualstudio\recipes\install.rb:27:in `each'
  C:\chef\cookbooks\visualstudio\recipes\install.rb:27:in `from_file'
  C:\chef\cookbooks\visualstudio\recipes\default.rb:32:in `from_file'
 
Relevant File Content:
----------------------
C:\chef\cookbooks\visualstudio\recipes\install.rb:
 
25:
26:  # Install each specified edition/version
27:  installs.each do |install|
28:    version = install['edition']
29:    edition = install['version']
30:
31:    install_url = File.join(node['visualstudio']['source'],
32>>                         node['visualstudio'][version][edition]['filename'])
33:  #  install_url = node['visualstudio']['source']
34:
35:    visualstudio_edition "visualstudio_#{version}_#{edition}" do
36:      edition edition
37:      version version
38:      install_dir node['visualstudio'][version]['install_dir']
39:      source install_url
40:      product_key node['visualstudio'][version][edition]['product_key']
41:      package_name node['visualstudio'][version][edition]['package_name']
 
 
Running handlers:
[2016-03-16T20:28:51+00:00] ERROR: Running exception handlers
Running handlers complete
[2016-03-16T20:28:51+00:00] ERROR: Exception handlers complete
Chef Client failed. 0 resources updated in 13 seconds
[2016-03-16T20:28:51+00:00] FATAL: Stacktrace dumped to C:/chef/chef-stacktrace.out
[2016-03-16T20:28:51+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2016-03-16T20:28:51+00:00] FATAL: NoMethodError: undefined method `[]' for nil:NilClass

**Comment by sneal** [comment]
In addition to setting the edition attribute to 'community', did you set the version attribute to '2015'?

```
node.override['visualstudio']['version'] = '2015'
node.override['visualstudio']['edition'] = 'community'
```

**Comment by rajeshapt** [comment]
Yes I did set the version to 2015

**Comment by sneal** [comment]
Can't reproduce this and test-kitchen is passing with same configuration.
