### ISSUE TITLE
32/64-bit check in minitest always results in 32-bit

### ISSUE THREAD

**Issue by cpx** [daptiv/visualstudio#56]
First off, I'm a newbie with Chef and my Ruby knowledge is pretty superficial :)

Anyway. I've run this cookbook repeatedly for the past week as part of setting up a Vagrant box. Initially it worked great, but since yesterday, for some hitherto unknown reason, it began failing in the post-install minitest. When searching the registry for VS2015, the test didn't find anything even though the install was successful. After some debugging, I figured out that the test was reading from the 32-bit registry instead of the 64-bit registry. I managed to narrow it down to this line of code:
`if node['kernel']['machine'] == :x86_64`
https://github.com/daptiv/visualstudio/blob/7b98848cabada29e19fa910c6769774a11170680/files/default/test/spec_helper.rb#L44

When I run the cookbook now, that statement evaluates to false (previously it seems to not have), even though it's executed in a 64-bit environment. I checked the source code of chef/ohai (which, if I understand things correctly, is the source of that value) and the value is set like this:
`kernel[:machine] = "x86_64"`
https://github.com/chef/ohai/blob/ac9f5a2ae4ada9f2e6e821418ed3a9039bda9a91/lib/ohai/plugins/kernel.rb#L83

As far as my Ruby knowledge goes, that's exactly what should happen, since :x86_64 is not equal to "x86_64". When I changed spec_helper.rb to compare against the string "x86_64" instead, everything worked again.

So my question is (sorry for the long prelude): Shouldn't this check be `if node['kernel']['machine'] == "x86_64"` instead? Looking at the source code of the cookbook and chef/ohai, I can't see how this could ever have worked, but it obviously did, which is why I'm asking instead of sending a PR :)

**Comment by sneal** [comment]
@cpx You're absolutely right, it is a string and not a symbol. So yeah, this is a bug. Did you upgrade from the 32bit version of Chef client to the 64bit version?

**Comment by cpx** [comment]
Nope, no upgrades that I'm aware of at least. It stopped working after doing vagrant destroy/up.
