### ISSUE TITLE
enable_nuget_package_restore not idempotent

### ISSUE THREAD

**Issue by petewilcock** [daptiv/visualstudio#58]
Every time I run the cookbook, the value of enable_nuget_package_restore, regardless of whether it's true or false, is set and is not idempotent. 

I have manually checked %EnableNuGetPackageRestore% and it is false, and set to false as a force_override attribute in my cookbook, yet it still sets this every run. Looking at the nuget recipe I can't work out why this is the case?

**Comment by sneal** [comment]
Looks like its [comparing a bool to a string](https://github.com/daptiv/visualstudio/blob/master/recipes/nuget.rb#L27). You can see below it does a proper to_s on the attribute but not in the setx guard.

**Comment by sneal** [comment]
Fixed by https://github.com/windowschefcookbooks/visualstudio/pull/4
