### ISSUE TITLE
How do I customise the AdminDeployment file?

### ISSUE THREAD

**Issue by petewilcock** [daptiv/visualstudio#59]
There is nothing in the documentation that specifies how to do this, and looking at all of the recipes and the resources I can't work out if this is even possible. How do I specify what VS components I want to install?!

**Comment by sneal** [comment]
@petewilcock This [isn't currently supported](https://github.com/daptiv/visualstudio/blob/master/providers/edition.rb#L81), but a PR would be welcomed.

**Comment by petewilcock** [comment]
OK great, I think I can do this. The installer just needs /InstallSelectableItems passed (I think) which can be built from an attribute with default values. Not sure if that would get overridden by the AdminDeployment.xml? But if all of the install arguments can be passed on the command line, would that render it redundant?

**Comment by sneal** [comment]
Here's a possibility. To provide a custom AdminDeployment.xml you would likely create a wrapper cookbook. We could modify the visualstudio cookbook to take a template_cookbook parameter to pass to the [cookbook_file resource](https://github.com/daptiv/visualstudio/blob/master/providers/edition.rb#L85).

```
def create_vs_admin_deployment_file
  config_source = "#{new_resource.version}/AdminDeployment-#{new_resource.edition}.xml"
  config_path = win_friendly_path(::File.join(extracted_iso_dir, 'AdminDeployment.xml'))

  # Create installation config file
  cookbook_file config_path do
    source config_source
    cookbook new_resource.template_cookbook if new_resource.template_cookbook
    action :create
  end

  config_path
end
```

The wrapper cookbook would just put the new template in the same directory structure as the visualstudio cookbook.

**Comment by petewilcock** [comment]
I'm almost with you but not quite. If we're using the cookbook_file resource to pull in a pre-customised AdminDeployment.xml, why do we need to modify the existing visualstudio cookbook at all? Can we not just place the cookbook_file in the vs cookbook template directory structure during the run?

**Comment by sneal** [comment]
You _could_ place a new template in the vs cookbook template directory, but typically you'd want to avoid customizing the vs cookbook because of upgrades. Anytime you upgrade the vs cookbook from SuperMarket (or from here) you'll need to remember to re-add in your customization. Its also a cleaner pattern to have a [wrapper cookbook](https://www.chef.io/blog/2013/12/03/doing-wrapper-cookbooks-right/).

**Comment by petewilcock** [comment]
Sorry -  I get what you're saying about the function of the wrapper. In my example it's the wrapper that's placing the custom AdminDeployment.xml into the VS-cookbook (which is what you were suggesting?)

Or are you suggesting the wrapper cookbook have it's own (but structurally identical) /files/ path with AdminDeployment.xml therein which is referenced as a parameter?

If that's the case, I understand, although it somehow feels a bit clunky to achieve the result.

**Comment by sneal** [comment]
I was suggesting option 2, but I get what you're saying about the lack of inflexibility. I'm not sure what you mean by "placing the custom AdminDeployment.xml into the VS-cookbook". Perhaps you can put together a quick PR (even if it doesn't work/pass tests) of what you're thinking, it'll probably make the discussion easier.

**Comment by petewilcock** [comment]
I literally mean doing a:
```
 file 'C:\chef\cache\cookbooks\visualstudio\files\default\2015\AdminDeployment-enterprise.xml' do
    source '/path/or/url/to/my/config.xml'
end
```
Assuming, of course, such a ninja insertion would even work. Now I think about it your suggestion is the more elegant ;)

I will put together a PR along your lines.

**Comment by sneal** [comment]
Now supported via attributes https://github.com/windowschefcookbooks/visualstudio/commit/b97ed50db19684a91c48a6f29f95c1e43fce9c4b
